from fpdf import FPDF
from datetime import date
from decimal import Decimal

class DigestPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(29, 158, 117) # Branded teal
        self.cell(0, 10, 'Doers — Daily Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Doers', 0, 0, 'C')

def generate_digest_pdf(gym_name, collections, expired_count, expiring_count) -> bytes:
    pdf = DigestPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    
    pdf.cell(200, 10, txt=f"Gym: {gym_name}", ln=1)
    pdf.cell(200, 10, txt=f"Date: {date.today()}", ln=1)
    pdf.ln(10)
    
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(200, 10, txt="Yesterday's Collections", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(200, 10, txt=f"Total: {collections}", ln=1)
    pdf.ln(5)
    
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(200, 10, txt="Summary", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(200, 10, txt=f"Members expired yesterday: {expired_count}", ln=1)
    pdf.cell(200, 10, txt=f"Members expiring soon: {expiring_count}", ln=1)
    
    return pdf.output(dest='S').encode('latin-1')
