from fpdf import FPDF
from datetime import date
from decimal import Decimal
from typing import List

class DigestPDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(29, 158, 117)  # teal
        self.cell(0, 10, 'Doers — Daily Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by Doers', 0, 0, 'C')

def generate_digest_pdf(
    gym_name: str,
    collections_total: Decimal,
    collections_breakdown: dict,         # {"cash": 500, "upi": 200}
    expired_members: List[dict],         # [{"name":...,"phone":...,"plan":...}]
    expiring_soon: List[dict]            # [{"name":...,"phone":...,"plan":...,"end_date":...}]
) -> bytes:
    pdf = DigestPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title block
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=12)
    pdf.cell(200, 10, txt=f"Gym: {gym_name}", ln=1)
    pdf.cell(200, 10, txt=f"Date: {date.today()}", ln=1)
    pdf.ln(10)

    # ---- Section 1: Yesterday's Collections ----
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(200, 10, "Yesterday's Collections", ln=1)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(200, 10, f"Total: Rs. {collections_total:,.2f}", ln=1)
    pdf.ln(3)

    # Breakdown table
    col_widths = [60, 60]
    pdf.set_font("Helvetica", 'B', 9)
    pdf.cell(col_widths[0], 8, "Payment Method", border=1)
    pdf.cell(col_widths[1], 8, "Amount (Rs.)", border=1)
    pdf.ln()
    pdf.set_font("Helvetica", size=9)
    total_check = Decimal(0)
    for method, amount in collections_breakdown.items():
        pdf.cell(col_widths[0], 8, method, border=1)
        pdf.cell(col_widths[1], 8, f"{amount:,.2f}", border=1)
        pdf.ln()
        total_check += amount
    pdf.cell(col_widths[0], 8, "Total", border=1)
    pdf.cell(col_widths[1], 8, f"{total_check:,.2f}", border=1)
    pdf.ln(10)

    # ---- Section 2: Expired Yesterday ----
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(200, 10, "Expired Yesterday", ln=1)
    if not expired_members:
        pdf.set_font("Helvetica", size=9)
        pdf.cell(200, 10, "No members expired.", ln=1)
    else:
        col_w = [60, 50, 70]
        pdf.set_font("Helvetica", 'B', 9)
        pdf.cell(col_w[0], 8, "Member", border=1)
        pdf.cell(col_w[1], 8, "Phone", border=1)
        pdf.cell(col_w[2], 8, "Plan", border=1)
        pdf.ln()
        pdf.set_font("Helvetica", size=9)
        for m in expired_members:
            pdf.cell(col_w[0], 8, m["name"], border=1)
            pdf.cell(col_w[1], 8, m["phone"], border=1)
            pdf.cell(col_w[2], 8, m["plan"], border=1)
            pdf.ln()
    pdf.ln(10)

    # ---- Section 3: Expiring in 48 hours ----
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(200, 10, "Expiring in 48 hours", ln=1)
    if not expiring_soon:
        pdf.set_font("Helvetica", size=9)
        pdf.cell(200, 10, "No members expiring soon.", ln=1)
    else:
        col_w = [55, 45, 50, 40]
        pdf.set_font("Helvetica", 'B', 9)
        pdf.cell(col_w[0], 8, "Member", border=1)
        pdf.cell(col_w[1], 8, "Phone", border=1)
        pdf.cell(col_w[2], 8, "Plan", border=1)
        pdf.cell(col_w[3], 8, "End Date", border=1)
        pdf.ln()
        pdf.set_font("Helvetica", size=9)
        for m in expiring_soon:
            pdf.cell(col_w[0], 8, m["name"], border=1)
            pdf.cell(col_w[1], 8, m["phone"], border=1)
            pdf.cell(col_w[2], 8, m["plan"], border=1)
            pdf.cell(col_w[3], 8, str(m["end_date"]), border=1)
            pdf.ln()

    return pdf.output(dest='S').encode('latin-1')