"""Add modern member profile fields

Revision ID: 157e09159795
Revises: 63b454cd56b7
Create Date: 2026-06-10 19:07:00.412910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '157e09159795'
down_revision: Union[str, Sequence[str], None] = '63b454cd56b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('home_branch_id', sa.UUID(), nullable=True))
    op.alter_column('members', 'gym_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_members_org_branch_id', 'members', ['org_id', 'home_branch_id'], unique=False)
    op.create_index('ix_members_org_status', 'members', ['org_id', 'status'], unique=False)
    op.drop_constraint('members_updated_by_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_created_by_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'org_branches', ['home_branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_created_by_fkey', 'members', 'gym_owners', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('members_updated_by_fkey', 'members', 'gym_owners', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_members_org_status', table_name='members')
    op.drop_index('ix_members_org_branch_id', table_name='members')
    op.alter_column('members', 'gym_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('members', 'home_branch_id')
    # ### end Alembic commands ###
