"""add owner and refresh_tokens tables

Revision ID: 165c866267fb
Revises: aa9303384b66
Create Date: 2026-05-13 12:58:30.582799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '165c866267fb'
down_revision: Union[str, Sequence[str], None] = 'aa9303384b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type manually
    facility_type_enum = sa.Enum('gym', 'yoga_studio', 'crossfit_box', 'swimming_pool', 'martial_arts', 'dance_studio', 'sports_academy', 'multi_sport', 'others', name='facilitytype')
    facility_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index('ix_owners_org_id', 'owners', ['org_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_owner_id', 'refresh_tokens', ['owner_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('organizations', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    
    # Use postgresql casting for altering column type to enum
    op.execute("ALTER TABLE organizations ALTER COLUMN facility_type TYPE facilitytype USING facility_type::facilitytype")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE organizations ALTER COLUMN facility_type TYPE VARCHAR(30)")
    
    op.alter_column('organizations', 'pan_number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_owner_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_owners_org_id', table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    
    # Drop enum type
    op.execute("DROP TYPE facilitytype")
    # ### end Alembic commands ###
