"""Add cover upload and audit generalization

Revision ID: 371b1a44a328
Revises: f6b19eae1a7c
Create Date: 2026-05-18 14:13:14.374791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '371b1a44a328'
down_revision: Union[str, Sequence[str], None] = 'f6b19eae1a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Rename the ENUM type
    op.execute("ALTER TYPE logo_status_enum RENAME TO asset_status_enum")

    op.create_table('organization_asset_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), server_default=sa.text("'logo'"), nullable=False),
    sa.Column('old_s3_key', sa.String(length=255), nullable=True),
    sa.Column('new_s3_key', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_asset_audit_org_id'), 'organization_asset_audit', ['org_id'], unique=False)
    op.drop_index(op.f('ix_organization_logo_audit_org_id'), table_name='organization_logo_audit')
    op.drop_table('organization_logo_audit')
    op.add_column('organizations', sa.Column('cover_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('cover_mobile_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('cover_tablet_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('cover_desktop_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('cover_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('cover_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='asset_status_enum'), nullable=True))
    op.add_column('organizations', sa.Column('cover_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('cover_updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'gym_owners', ['cover_updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'cover_updated_by')
    op.drop_column('organizations', 'cover_updated_at')
    op.drop_column('organizations', 'cover_status')
    op.drop_column('organizations', 'cover_meta')
    op.drop_column('organizations', 'cover_desktop_key')
    op.drop_column('organizations', 'cover_tablet_key')
    op.drop_column('organizations', 'cover_mobile_key')
    op.drop_column('organizations', 'cover_key')
    op.create_table('organization_logo_audit',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_s3_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('new_s3_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['gym_owners.id'], name=op.f('organization_logo_audit_changed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('organization_logo_audit_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_logo_audit_pkey'))
    )
    op.create_index(op.f('ix_organization_logo_audit_org_id'), 'organization_logo_audit', ['org_id'], unique=False)
    op.drop_index(op.f('ix_organization_asset_audit_org_id'), table_name='organization_asset_audit')
    op.drop_table('organization_asset_audit')

    # Rename enum back to logo_status_enum
    op.execute("ALTER TYPE asset_status_enum RENAME TO logo_status_enum")
    # ### end Alembic commands ###
