"""Add Payment.idempotency_key with partial unique index

Revision ID: 569750b69ee4
Revises: bf980e6920ab
Create Date: 2026-05-07 22:41:51.232257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569750b69ee4'
down_revision: Union[str, Sequence[str], None] = 'bf980e6920ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index('ix_payment_idempotency', 'payments', ['org_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_idempotency', table_name='payments', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('payments', 'idempotency_key')
    # ### end Alembic commands ###
