"""Migrate legacy PAN to secure registrations and add entity_type

Revision ID: 56c708ff25ef
Revises: c36d1a05c5ef
Create Date: 2026-05-16 18:51:16.105700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c708ff25ef'
down_revision: Union[str, Sequence[str], None] = 'c36d1a05c5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_registrations', sa.Column('entity_type', sa.String(length=1), nullable=True))
    op.drop_index(op.f('ix_organizations_pan'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_pan_number'), table_name='organizations')
    op.drop_column('organizations', 'pan_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('pan_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_organizations_pan_number'), 'organizations', ['pan_number'], unique=True)
    op.create_index(op.f('ix_organizations_pan'), 'organizations', ['pan_number'], unique=False)
    op.drop_column('organization_registrations', 'entity_type')
    # ### end Alembic commands ###
