"""Add organization slug and facility type reference tables

Revision ID: 9eabb30e0c81
Revises: fe7fc58f99fd
Create Date: 2026-05-16 18:31:24.562714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eabb30e0c81'
down_revision: Union[str, Sequence[str], None] = 'fe7fc58f99fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('system_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('icon_key', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('gym_facility_types',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('facility_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_type_id'], ['facility_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_id', 'facility_type_id')
    )
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('gyms', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint('uix_gym_org_name', 'gyms', ['org_id', 'name'])
    op.add_column('organizations', sa.Column('slug', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'slug')
    op.drop_constraint('uix_gym_org_name', 'gyms', type_='unique')
    op.alter_column('gyms', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('gym_facility_types')
    op.drop_table('facility_types')
    # ### end Alembic commands ###
