"""Add missing columns and DeviceStatus enum

Revision ID: a30fac8c9c18
Revises: 2de6f8fabe00
Create Date: 2026-05-07 22:17:17.445544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30fac8c9c18'
down_revision: Union[str, Sequence[str], None] = '2de6f8fabe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    devicestatus_enum = sa.Enum('online', 'offline', 'maintenance', name='devicestatus')
    devicestatus_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('devices', sa.Column('status', devicestatus_enum, server_default='offline', nullable=False))
    op.add_column('devices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('devices', 'is_online')
    op.add_column('members', sa.Column('email', sa.String(), nullable=True))
    op.add_column('members', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('payments', sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscription_plans', sa.Column('grace_period_days', sa.Integer(), server_default=sa.text('3'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'grace_period_days')
    op.drop_column('payments', 'payment_date')
    op.drop_column('members', 'is_active')
    op.drop_column('members', 'email')
    op.add_column('devices', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('devices', 'device_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('devices', 'deleted_at')
    op.drop_column('devices', 'status')
    # ### end Alembic commands ###
