"""Initial Schema

Revision ID: aa9303384b66
Revises: 
Create Date: 2026-05-10 01:05:09.325825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa9303384b66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=False),
    sa.Column('tier', sa.Enum('basic', 'pro', 'elite', name='orgtier'), nullable=False),
    sa.Column('facility_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_organizations_pan', 'organizations', ['pan_number'], unique=False)
    op.create_index(op.f('ix_organizations_pan_number'), 'organizations', ['pan_number'], unique=True)
    op.create_table('gyms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gymu_id', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gyms_gymu_id'), 'gyms', ['gymu_id'], unique=True)
    op.create_index('ix_gyms_org_id', 'gyms', ['org_id'], unique=False)
    op.create_table('branch_tax_settings',
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('gst_number', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sac_code', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_id'),
    sa.UniqueConstraint('gst_number')
    )
    op.create_table('gym_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'trainer', 'receptionist', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_gym_owners_org_email')
    )
    op.create_index('ix_gym_owners_org_id', 'gym_owners', ['org_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_freeze_days', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscription_plans_gym_id', 'subscription_plans', ['gym_id'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('imported_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='importstatus'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('errors_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_software', sa.String(length=50), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['imported_by'], ['gym_owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_logs_gym_id', 'import_logs', ['gym_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('member_uid', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fingerprint_id', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'frozen', 'expired', 'blocked', name='memberstatus'), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_migrated', sa.Boolean(), nullable=False),
    sa.Column('migrated_source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_uid'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_index('ix_members_email', 'members', ['email'], unique=False)
    op.create_index('ix_members_gym_fingerprint', 'members', ['gym_id', 'fingerprint_id'], unique=False)
    op.create_index('ix_members_gym_id', 'members', ['gym_id'], unique=False)
    op.create_index('ix_members_gym_member_uid', 'members', ['gym_id', 'member_uid'], unique=True)
    op.create_index('ix_members_gym_phone', 'members', ['gym_id', 'phone'], unique=False)
    op.create_index('ix_members_gym_qr_token', 'members', ['gym_id', 'qr_token'], unique=True)
    op.create_index('ix_members_gym_status', 'members', ['gym_id', 'status'], unique=False)
    op.create_index('ix_members_org_id', 'members', ['org_id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('scan_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('check_in_method', sa.Enum('qr', 'fingerprint', 'manual', 'rfid', 'face', 'door_lock', name='checkinmethod'), nullable=False),
    sa.Column('access_granted', sa.Boolean(), nullable=False),
    sa.Column('denial_reason', sa.Enum('subscription_expired', 'no_active_subscription', 'account_frozen', 'not_found', name='attendancedenialreason'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_gym_id', 'attendance_logs', ['gym_id'], unique=False)
    op.create_index('ix_attendance_gym_scan', 'attendance_logs', ['gym_id', sa.literal_column('scan_time DESC')], unique=False)
    op.create_index('ix_attendance_member_id', 'attendance_logs', ['member_id'], unique=False)
    op.create_index('ix_attendance_scan_time', 'attendance_logs', ['scan_time'], unique=False)
    op.create_table('member_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_member_date', 'member_measurements', ['member_id', sa.literal_column('measured_on DESC')], unique=False)
    op.create_table('member_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('freeze_start_date', sa.Date(), nullable=True),
    sa.Column('freeze_end_date', sa.Date(), nullable=True),
    sa.Column('total_freeze_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'frozen', 'cancelled', 'pending', name='subscriptionstatus'), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_subs_gym_id', 'member_subscriptions', ['gym_id'], unique=False)
    op.create_index('ix_member_subs_gym_status_end', 'member_subscriptions', ['gym_id', 'status', 'end_date'], unique=False)
    op.create_index('ix_member_subs_member_status', 'member_subscriptions', ['member_id', 'status'], unique=False)
    op.create_table('member_freeze_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('freeze_start', sa.Date(), nullable=False),
    sa.Column('freeze_end', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('requested', 'active', 'completed', 'cancelled', name='freezestatus'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['member_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_freeze_logs_member_sub', 'member_freeze_logs', ['member_id', 'subscription_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('collected_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'upi', 'card', 'bank_transfer', 'cheque', 'online', name='paymentmethod'), nullable=False),
    sa.Column('payment_type', sa.Enum('subscription', 'registration', 'addon', 'penalty', 'refund', name='paymenttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('transaction_reference', sa.String(), nullable=True),
    sa.Column('razorpay_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_migrated', sa.Boolean(), nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collected_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['member_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_gym_date_status', 'payments', ['gym_id', sa.literal_column('payment_date DESC'), 'status'], unique=False)
    op.create_index('ix_payments_gym_member', 'payments', ['gym_id', 'member_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gym_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('invoice_type', sa.Enum('bill_of_supply', 'tax_invoice', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'void', name='invoicestatus'), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['member_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_gym_issued_at', 'invoices', ['gym_id', sa.literal_column('issued_at DESC')], unique=False)
    op.create_index('ix_invoices_gym_member', 'invoices', ['gym_id', 'member_id'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_gym_member', table_name='invoices')
    op.drop_index('ix_invoices_gym_issued_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_payments_gym_member', table_name='payments')
    op.drop_index('ix_payments_gym_date_status', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_freeze_logs_member_sub', table_name='member_freeze_logs')
    op.drop_table('member_freeze_logs')
    op.drop_index('ix_member_subs_member_status', table_name='member_subscriptions')
    op.drop_index('ix_member_subs_gym_status_end', table_name='member_subscriptions')
    op.drop_index('ix_member_subs_gym_id', table_name='member_subscriptions')
    op.drop_table('member_subscriptions')
    op.drop_index('ix_measurements_member_date', table_name='member_measurements')
    op.drop_table('member_measurements')
    op.drop_index('ix_attendance_scan_time', table_name='attendance_logs')
    op.drop_index('ix_attendance_member_id', table_name='attendance_logs')
    op.drop_index('ix_attendance_gym_scan', table_name='attendance_logs')
    op.drop_index('ix_attendance_gym_id', table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index('ix_members_org_id', table_name='members')
    op.drop_index('ix_members_gym_status', table_name='members')
    op.drop_index('ix_members_gym_qr_token', table_name='members')
    op.drop_index('ix_members_gym_phone', table_name='members')
    op.drop_index('ix_members_gym_member_uid', table_name='members')
    op.drop_index('ix_members_gym_id', table_name='members')
    op.drop_index('ix_members_gym_fingerprint', table_name='members')
    op.drop_index('ix_members_email', table_name='members')
    op.drop_table('members')
    op.drop_index('ix_import_logs_gym_id', table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index('ix_subscription_plans_gym_id', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('ix_gym_owners_org_id', table_name='gym_owners')
    op.drop_table('gym_owners')
    op.drop_table('branch_tax_settings')
    op.drop_index('ix_gyms_org_id', table_name='gyms')
    op.drop_index(op.f('ix_gyms_gymu_id'), table_name='gyms')
    op.drop_table('gyms')
    op.drop_index(op.f('ix_organizations_pan_number'), table_name='organizations')
    op.drop_index('ix_organizations_pan', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
