"""Add Staff.name and SubscriptionStatus.frozen

Revision ID: bf980e6920ab
Revises: a30fac8c9c18
Create Date: 2026-05-07 22:26:11.568291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf980e6920ab'
down_revision: Union[str, Sequence[str], None] = 'a30fac8c9c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('staff', sa.Column('name', sa.String(), nullable=True))
    # Alembic cannot auto-detect new enum values — must be done manually
    op.execute("ALTER TYPE subscriptionstatus ADD VALUE IF NOT EXISTS 'frozen'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'name')
    # ### end Alembic commands ###
