"""Refactor BranchTaxSettings for secure multi-tax support

Revision ID: c36d1a05c5ef
Revises: f8200152d7f5
Create Date: 2026-05-16 18:48:50.197999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36d1a05c5ef'
down_revision: Union[str, Sequence[str], None] = 'f8200152d7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_tax_settings', sa.Column('tax_type', sa.String(length=10), nullable=False))
    op.add_column('branch_tax_settings', sa.Column('tax_id_encrypted', sa.Text(), nullable=False))
    op.add_column('branch_tax_settings', sa.Column('tax_id_masked', sa.String(length=20), nullable=False))
    op.add_column('branch_tax_settings', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('branch_tax_settings', sa.Column('filing_frequency', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('branch_tax_settings_gst_number_key'), 'branch_tax_settings', type_='unique')
    op.drop_column('branch_tax_settings', 'gst_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_tax_settings', sa.Column('gst_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('branch_tax_settings_gst_number_key'), 'branch_tax_settings', ['gst_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('branch_tax_settings', 'filing_frequency')
    op.drop_column('branch_tax_settings', 'is_verified')
    op.drop_column('branch_tax_settings', 'tax_id_masked')
    op.drop_column('branch_tax_settings', 'tax_id_encrypted')
    op.drop_column('branch_tax_settings', 'tax_type')
    # ### end Alembic commands ###
