"""Add tagline and description to organization

Revision ID: cc6b6d4beb59
Revises: 9eabb30e0c81
Create Date: 2026-05-16 18:33:53.358843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6b6d4beb59'
down_revision: Union[str, Sequence[str], None] = '9eabb30e0c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('tagline', sa.String(length=150), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'tagline')
    # ### end Alembic commands ###
