"""Add business_type to Organization

Revision ID: ebc84c25cf68
Revises: f5753bc3014a
Create Date: 2026-05-18 11:48:43.327773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc84c25cf68'
down_revision: Union[str, Sequence[str], None] = 'f5753bc3014a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('business_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'business_type')
    # ### end Alembic commands ###
