"""Add website and social links to organization

Revision ID: f5753bc3014a
Revises: 56c708ff25ef
Create Date: 2026-05-16 18:53:39.074651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5753bc3014a'
down_revision: Union[str, Sequence[str], None] = '56c708ff25ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('website_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('organizations', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'social_links')
    op.drop_column('organizations', 'website_verified')
    op.drop_column('organizations', 'website_url')
    # ### end Alembic commands ###
