"""Add composite indexes for multi-tenant isolation and performance

Revision ID: f69823ccf725
Revises: 001_initial_schema
Create Date: 2026-05-09 19:56:35.784657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69823ccf725'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_tax_gst'), table_name='branch_tax_settings')
    op.create_unique_constraint(None, 'branch_tax_settings', ['gst_number'])
    op.drop_index(op.f('ix_invoices_gym_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_member_id'), table_name='invoices')
    op.create_index('ix_invoices_gym_issued_at', 'invoices', ['gym_id', sa.literal_column('issued_at DESC')], unique=False)
    op.create_index('ix_invoices_gym_member', 'invoices', ['gym_id', 'member_id'], unique=False)
    op.create_unique_constraint(None, 'invoices', ['invoice_number'])
    op.drop_index(op.f('ix_member_subs_end_date'), table_name='member_subscriptions')
    op.drop_index(op.f('ix_member_subs_gym_status'), table_name='member_subscriptions')
    op.create_index('ix_member_subs_gym_status_end', 'member_subscriptions', ['gym_id', 'status', 'end_date'], unique=False)
    op.drop_index(op.f('ix_members_member_uid'), table_name='members')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.drop_index(op.f('ix_members_qr_token'), table_name='members')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.create_index('ix_members_gym_fingerprint', 'members', ['gym_id', 'fingerprint_id'], unique=False)
    op.create_index('ix_members_gym_member_uid', 'members', ['gym_id', 'member_uid'], unique=True)
    op.create_index('ix_members_gym_qr_token', 'members', ['gym_id', 'qr_token'], unique=True)
    op.create_index('ix_members_gym_status', 'members', ['gym_id', 'status'], unique=False)
    op.create_unique_constraint(None, 'members', ['qr_token'])
    op.create_unique_constraint(None, 'members', ['member_uid'])
    op.drop_index(op.f('ix_organizations_pan'), table_name='organizations')
    op.create_index('ix_organizations_pan', 'organizations', ['pan_number'], unique=False)
    op.create_index(op.f('ix_organizations_pan_number'), 'organizations', ['pan_number'], unique=True)
    op.drop_index(op.f('ix_payments_gym_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_gym_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_member_id'), table_name='payments')
    op.create_index('ix_payments_gym_date_status', 'payments', ['gym_id', sa.literal_column('payment_date DESC'), 'status'], unique=False)
    op.create_index('ix_payments_gym_member', 'payments', ['gym_id', 'member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_gym_member', table_name='payments')
    op.drop_index('ix_payments_gym_date_status', table_name='payments')
    op.create_index(op.f('ix_payments_member_id'), 'payments', ['member_id'], unique=False)
    op.create_index(op.f('ix_payments_gym_id'), 'payments', ['gym_id'], unique=False)
    op.create_index(op.f('ix_payments_gym_date'), 'payments', ['gym_id', sa.literal_column('payment_date DESC')], unique=False)
    op.drop_index(op.f('ix_organizations_pan_number'), table_name='organizations')
    op.drop_index('ix_organizations_pan', table_name='organizations')
    op.create_index(op.f('ix_organizations_pan'), 'organizations', ['pan_number'], unique=True)
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_index('ix_members_gym_status', table_name='members')
    op.drop_index('ix_members_gym_qr_token', table_name='members')
    op.drop_index('ix_members_gym_member_uid', table_name='members')
    op.drop_index('ix_members_gym_fingerprint', table_name='members')
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_index(op.f('ix_members_qr_token'), 'members', ['qr_token'], unique=True)
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=False)
    op.create_index(op.f('ix_members_member_uid'), 'members', ['member_uid'], unique=True)
    op.drop_index('ix_member_subs_gym_status_end', table_name='member_subscriptions')
    op.create_index(op.f('ix_member_subs_gym_status'), 'member_subscriptions', ['gym_id', 'status'], unique=False)
    op.create_index(op.f('ix_member_subs_end_date'), 'member_subscriptions', ['end_date'], unique=False)
    op.drop_constraint(None, 'invoices', type_='unique')
    op.drop_index('ix_invoices_gym_member', table_name='invoices')
    op.drop_index('ix_invoices_gym_issued_at', table_name='invoices')
    op.create_index(op.f('ix_invoices_member_id'), 'invoices', ['member_id'], unique=False)
    op.create_index(op.f('ix_invoices_gym_id'), 'invoices', ['gym_id'], unique=False)
    op.drop_constraint(None, 'branch_tax_settings', type_='unique')
    op.create_index(op.f('ix_branch_tax_gst'), 'branch_tax_settings', ['gst_number'], unique=True)
    # ### end Alembic commands ###
