"""Add logo upload and audit

Revision ID: f6b19eae1a7c
Revises: ebc84c25cf68
Create Date: 2026-05-18 13:58:01.537367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b19eae1a7c'
down_revision: Union[str, Sequence[str], None] = 'ebc84c25cf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_LOGO_UPDATED_BY_FK = 'organizations_logo_updated_by_fkey'


def _require_logo_updated_by_fk() -> None:
    bind = op.get_bind()
    row = bind.execute(
        sa.text(
            """
            SELECT
                constraint_data.contype::text AS constraint_type,
                constraint_data.confdeltype::text AS delete_action,
                source_attribute.attname::text AS source_column,
                target_namespace.nspname::text AS target_schema,
                target_relation.relname::text AS target_table,
                target_attribute.attname::text AS target_column
            FROM pg_catalog.pg_constraint AS constraint_data
            JOIN pg_catalog.pg_class AS source_relation
              ON source_relation.oid = constraint_data.conrelid
            JOIN pg_catalog.pg_namespace AS source_namespace
              ON source_namespace.oid = source_relation.relnamespace
            JOIN pg_catalog.pg_class AS target_relation
              ON target_relation.oid = constraint_data.confrelid
            JOIN pg_catalog.pg_namespace AS target_namespace
              ON target_namespace.oid = target_relation.relnamespace
            JOIN pg_catalog.pg_attribute AS source_attribute
              ON source_attribute.attrelid = source_relation.oid
             AND source_attribute.attnum = constraint_data.conkey[1]
            JOIN pg_catalog.pg_attribute AS target_attribute
              ON target_attribute.attrelid = target_relation.oid
             AND target_attribute.attnum = constraint_data.confkey[1]
            WHERE source_namespace.nspname = 'public'
              AND source_relation.relname = 'organizations'
              AND constraint_data.conname = :constraint_name
              AND pg_catalog.array_length(constraint_data.conkey, 1) = 1
              AND pg_catalog.array_length(constraint_data.confkey, 1) = 1
            """
        ),
        {"constraint_name": _LOGO_UPDATED_BY_FK},
    ).mappings().one_or_none()
    expected = {
        "constraint_type": "f",
        "delete_action": "n",
        "source_column": "logo_updated_by",
        "target_schema": "public",
        "target_table": "gym_owners",
        "target_column": "id",
    }
    if row is None or dict(row) != expected:
        raise RuntimeError(
            "f6b19eae1a7c logo_updated_by FK drift before downgrade: "
            f"expected={expected!r}, observed={dict(row) if row is not None else None!r}"
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_logo_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('old_s3_key', sa.String(length=255), nullable=True),
    sa.Column('new_s3_key', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['gym_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_logo_audit_org_id'), 'organization_logo_audit', ['org_id'], unique=False)
    op.add_column('organizations', sa.Column('document_url', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('verification_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('organizations', sa.Column('logo_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('logo_thumb_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('logo_medium_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('logo_full_key', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('logo_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    logo_status_enum = postgresql.ENUM('pending', 'processing', 'ready', 'failed', name='logo_status_enum')
    logo_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('organizations', sa.Column('logo_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='logo_status_enum'), nullable=True))
    op.add_column('organizations', sa.Column('logo_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('logo_updated_by', sa.UUID(), nullable=True))
    op.create_foreign_key(_LOGO_UPDATED_BY_FK, 'organizations', 'gym_owners', ['logo_updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Validate the exact FK this revision owns before mutation. An unexpected
    # constraint is drift and must not be normalized by dropping an arbitrary FK.
    _require_logo_updated_by_fk()
    op.drop_constraint(_LOGO_UPDATED_BY_FK, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'logo_updated_by')
    op.drop_column('organizations', 'logo_updated_at')
    op.drop_column('organizations', 'logo_status')
    logo_status_enum = postgresql.ENUM('pending', 'processing', 'ready', 'failed', name='logo_status_enum')
    logo_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('organizations', 'logo_meta')
    op.drop_column('organizations', 'logo_full_key')
    op.drop_column('organizations', 'logo_medium_key')
    op.drop_column('organizations', 'logo_thumb_key')
    op.drop_column('organizations', 'logo_key')
    op.drop_column('organizations', 'verification_status')
    op.drop_column('organizations', 'document_url')
    op.drop_index(op.f('ix_organization_logo_audit_org_id'), table_name='organization_logo_audit')
    op.drop_table('organization_logo_audit')
    # ### end Alembic commands ###
