"""Add organization_registrations table for secure business IDs

Revision ID: f8200152d7f5
Revises: fe4199a51655
Create Date: 2026-05-16 18:46:20.101576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8200152d7f5'
down_revision: Union[str, Sequence[str], None] = 'fe4199a51655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id_type', sa.String(length=20), nullable=False),
    sa.Column('id_number_encrypted', sa.Text(), nullable=False),
    sa.Column('id_number_masked', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'id_type', 'id_number_encrypted', name='uix_org_reg_type_country')
    )
    op.create_index('ix_org_reg_org_id', 'organization_registrations', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_reg_org_id', table_name='organization_registrations')
    op.drop_table('organization_registrations')
    # ### end Alembic commands ###
