"""Add year_established to organization

Revision ID: fe4199a51655
Revises: cc6b6d4beb59
Create Date: 2026-05-16 18:38:13.512291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4199a51655'
down_revision: Union[str, Sequence[str], None] = 'cc6b6d4beb59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('year_established', sa.SMALLINT(), nullable=True))
    op.create_check_constraint(
        "check_year_established",
        "organizations",
        "year_established >= 1800 AND year_established <= EXTRACT(YEAR FROM CURRENT_DATE)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_year_established', 'organizations')
    op.drop_column('organizations', 'year_established')
    # ### end Alembic commands ###
