"""Add onboarding fields and trial subscriptions

Revision ID: fe7fc58f99fd
Revises: 6e8688afcbf8
Create Date: 2026-05-13 18:29:44.732140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe7fc58f99fd'
down_revision: Union[str, Sequence[str], None] = '6e8688afcbf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('trial_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('trial_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('grace_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hard_lock_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('soft_locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('hard_locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_trial_status_end', 'trial_subscriptions', ['status', 'trial_end'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['owners.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_org_action', 'audit_logs', ['organization_id', 'action'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('organizations', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('organizations', sa.Column('address_line1', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('address_line2', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('pincode', sa.String(length=6), nullable=True))
    op.add_column('organizations', sa.Column('country', sa.String(length=60), server_default=sa.text("'India'"), nullable=False))
    op.add_column('organizations', sa.Column('profile_completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('owners', sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('owners', sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.add_column('owners', sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'onboarding_completed_at')
    op.drop_column('owners', 'onboarding_completed')
    op.drop_column('owners', 'email_verified_at')
    op.drop_column('organizations', 'profile_completed')
    op.drop_column('organizations', 'country')
    op.drop_column('organizations', 'pincode')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'address_line2')
    op.drop_column('organizations', 'address_line1')
    op.drop_column('organizations', 'phone')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_org_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_trial_status_end', table_name='trial_subscriptions')
    op.drop_table('trial_subscriptions')
    # ### end Alembic commands ###
